MODE=standalone
UPSD_OPTIONS=""
UPSMON_OPTIONS=""

# [eatonelite]
#     driver = "usbhid-ups"
#     port = "auto"
#     desc = "UPS"
#     ignorelb
#     override.battery.charge.low=30

[nutdev-usb1]
	driver = "usbhid-ups"
	port = "auto"
	# vendorid = "0463"
	# productid = "FFFF"
	# product = "Protection Station"
	# serial = "AN2E49008"
	# vendor = "EATON"
	# bus = "003"
	# device = "003"
	# busport = "002"
    override.battery.charge.low=30
